#!/bin/bash
ENV="dev"
CLOUD=".phplake.com"
USERNAME=$1
PROJECT=$2
URL=$3
DOCROOT=/var/www/html/$ENV-$PROJECT-$USERNAME$CLOUD
DOCIDE=/var/www/html/ide-$USERNAME$CLOUD

git clone $URL $DOCROOT
chown -Rf $USERNAME:$USERNAME $DOCROOT
chmod 755 -R $DOCROOT

ln -s $DOCROOT $DOCIDE/workspace/
