#!/bin/bash
USERNAME=$1
DOCROOT=/var/www/html/$2
DOCIDE=/var/www/html/$3
URL=$4

git clone $URL $DOCROOT
chown -Rf $USERNAME:$USERNAME $DOCROOT
chmod 755 -R $DOCROOT

ln -s $DOCROOT $DOCIDE/workspace/
