#!/bin/bash
USERNAME=$1
DOCFOLDER=$2
DOCIDE=/var/www/html/$DOCFOLDER
useradd -m $USERNAME
git clone https://github.com/washim/Codiad.git $DOCIDE
rm -rf $DOCIDE/.git
chown -Rf $USERNAME:$USERNAME $DOCIDE
chmod 755 -R $DOCIDE
